# File: .github/workflows/grafana-deploy.yml
name: Deploy Grafana Application

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH for remote deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose file
        run: |
          scp -o StrictHostKeyChecking=no grafana/docker-compose.yaml ec2-user@${{ secrets.SERVER_ADDRESS }}:/home/ec2-user/grafana/

      - name: Deploy Grafana with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "
            cd /home/ec2-user/grafana && \
            docker compose pull && \
            docker compose up -d --force-recreate
          "

      - name: Wait for Grafana to start
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "
            echo 'Waiting for Grafana to start...' && \
            sleep 30 && \
            curl -f http://localhost:3000 || exit 1
          "

      - name: Clean up old Docker images
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "
            docker system prune -f --all --volumes"
