name: Deploy Grafana with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy-grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH for remote deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 1: Pull and deploy Grafana using Docker Compose
      - name: Deploy Grafana via Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "cd /home/ec2-user/grafana && docker-compose pull && docker-compose up -d"

      # Step 2: Test if Grafana is running
      - name: Test Grafana service
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "curl -f http://localhost:3000 || exit 1"

      # Step 3: Post-deployment tasks (Optional)
      - name: Run Grafana post-deployment tasks
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "docker exec grafana /bin/bash -c 'grafana-cli plugins list'"

      # Step 4: Clean up Docker images (Optional)
      - name: Clean up old Docker images
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "docker system prune -af"
