name: Deploy Nginx Config

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH for remote deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: Copy Nginx configuration to server
      run: |
        # Copia o arquivo de configuração para o diretório temporário
        scp -o StrictHostKeyChecking=no ./grafana.conf ec2-user@${{ secrets.SERVER_ADDRESS }}:/tmp/

    - name: Move Nginx config to the correct location with sudo
      run: |
        # Move o arquivo para o diretório correto /etc/nginx/conf.d/ usando sudo
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "sudo mv /tmp/grafana.conf /etc/nginx/conf.d/ && sudo chown root:root /etc/nginx/conf.d/grafana.conf"

    - name: Test Nginx configuration
      run: |
        # Testa se a configuração do Nginx está correta no servidor remoto
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "sudo nginx -t"

    - name: Restart Nginx
      run: |
        # Reinicia o Nginx no servidor remoto
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SERVER_ADDRESS }} "sudo systemctl restart nginx"
